spring:
  application:
    name: soieu

  datasource:
    url: jdbc:mysql://localhost:3306/soieu
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
